import 'package:flutter/material.dart';

class AppColors {
  static const Color primary = Color(0xFF0460D8);
  static const Color primarySubtle = Color(0xFFEAF3FF);
  static const Color primarySoft = Color(0x140460D8);
  static const Color white = Colors.white;
  static const Color black = Colors.black;
  static const Color grey = Color(0xFF6B7280);
  static const Color lightGrey = Color(0xFFF3F4F6);
  static const Color midGrey = Color.fromARGB(255, 207, 207, 207);
  static const Color darkGrey = Color(0xFF374151);
  static const Color text = Color(0xFF374151);
  static const Color textMuted = Color(0xFF6B7280);
  static const Color textSubtle = Color(0xFF9CA3AF);
  static const Color border = Color(0xFFE5E7EB);
  static const Color borderStrong = Color(0xFFCBD5E1);
  static const Color surface = Color(0xFFFFFBF7);
  static const Color surfaceElevated = Color(0xFFFFFFFF);
  static const Color background = Color(0xFFFFF8F0);
  static const Color warmBackground = Color(0xFFFFF8F0);
  static const Color warmYellow = Color(0xFFF4B942);
  static const Color moodGood = Color(0xFF2D9E54);
  static const Color moodOkay = Color(0xFFF59E0B);
  static const Color moodLow = Color(0xFFE85D3A);
  static const Color danger = Color(0xFFDC2626);
  static const Color warning = Color(0xFFF59E0B);
  static const Color success = Color(0xFF2D9E54);
  static const Color crisisBg = Color(0xFFFFF9F5);
  static const Color crisisSurface = Color(0xFFFFFFFF);
  static const Color crisisText = Color(0xFF2D2A26);
  static const Color crisisTextMuted = Color(0xFF6B7280);
  static const Color crisisPrimary = Color(0xFFE85D3A);
  static const Color crisisPrimaryHover = Color(0xFFD14A2A);
  static const Color crisisSubtle = Color(0xFFF5E6DF);
  static const Color crisisSafe = Color(0xFF2D9E54);
  static const Color crisisWarning = Color(0xFFF5A623);
  static const Color crisisDanger = Color(0xFFD9342B);
  static const Color crisisTextOnDark = Color(0xFFFFFFFF);
}
